pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()

        // ✅ локальные AAR из app/libs
        flatDir {
            dirs("app/libs")
        }
    }
}

rootProject.name = "weather"

include ':app'
include ':auth'
